project:
  type: website
  output-dir: _site

metadata-files: 
  - ./posts/_metadata.yml
toc: true
website:
  title: "BlogDen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zooxs
      - icon: instagram
        href: https://instagram.com/atensiden
format:
  html:
    theme: litera
    css: styles.css
    bibliography: ref.bib
    # csl: https://github.com/citation-style-language/styles/blob/master/apa-6th-edition.csl
    
language: bahasa.yml



