project:
  type: website
  output-dir: _site

metadata-files: 
  - ./posts/_metadata.yml
toc: true
website:
  title: "BlogDen"
  google-analytics:
    tracking-id: "G-B8MH87QSQ9"
    anonymize-ip: true
  navbar:
    right:
      # - icon: user
      #   href: about.qmd
      - icon: github
        href: https://github.com/zooxs
      - icon: instagram
        href: https://instagram.com/atensiden
      - icon: twitter
        href: https://twitter.com/pandumulyams
  
  page-footer: 
    left: 'Copyright 2023, Pandu Mulya Muhammad Syah'
    right: 
      - icon: github
        href: https://github.com/zooxs
      - icon: instagram
        href: https://instagram.com/atensiden
      - icon: twitter
        href: https://twitter.com/pandumulyams
format:
  html:
    theme: litera
    css: styles.css
    bibliography: ref.bib
    csl: apa.csl
    
# collections:
#   posts:
#     share: [twitter, linkedin]   
language: bahasa.yml



