---
title: "Membuat, Membaca dan Mengedit File Menggunakan Python"
description: |
   Ringkasan pengolahan file menggunakan *built-in function* pada Python.
categories: [Python, I/O]
date: 2022-10-07
---

# Pengenalan

Python termasuk ke dalam *general purpose programming languange* sehingga dapat digunakan untuk berbagai keperluan. Salah satu pemanfaatannya adalah pemrosesan file mulai dari pembuatan, pembacaan dan pengeditan dapat dilakukan bergantung jenis file yang diolah. Pada artikel ini ditunjukkan contoh pengolahan file tipe *plain text* atau file sederhana berisi tulisan (`.txt`) yang akan diproses menggunakan *built-in function* pada Python (`open()`) dan *context manager*.

# Fungsi `open()`

`open()` merupakan fungsi *built-in* (bawaan) pada Python. Fungsi ini bertujuan untuk membuka suatu file dengan mode tertentu seperti baca (*read*) atau tulis (*write*). Fungsi ini dapat dituliskan sebagai `open(path_file, mode)` dimana:

- `path_file` merupakan lokasi dari file yang akan digunakan seperti `simpel.txt` atau `folder1/folder2/simpel.txt` jika file berada dalam folder tertentu.
- `mode` pilihan operasi yang akan digunakan.

| Opsi | Tujuan                                                   |
|------|----------------------------------------------------------|
| 'r'  | Membaca file (*default*)                                 |
| 'w'  | Menulis file                                             |
| 'x'  | Pembuatan ekslusif, gagal jika file telah ada            |
| 'a'  | Menambahkan isi file di  akhir baris jika file telah ada |
| 'b'  | Mode binary                                              |
| 't'  | Mode teks (*default*)                                    |
| '+'  | Mengedit file (*write*, *reading*)                       |

: Mode opsi pada fungsi `open()`

Lebih lengkap dapat dilihat pada [sumber berikut](https://docs.python.org/3/library/functions.html#open) 

# *Context Manager* pada Python

*Context manager* merupakan salah satu metode yang digunakan untuk mengatasi *memory leak* dari *external resources* (file dan koneksi internet). Metode ini dapat mengelolah *external resources* dengan menutupnya setelah tidak digunakan lagi sehingga dapat menghindari terjadinya *memory leak*. Salah satu pendekatan yang umum digunakan pada metode ini adalah menggunakan konstruktor `with` [@Python2021Context].

# Pemrosesan File

## Pembuatan (*write*) file

```{python}
with open('simpel.txt', 'w') as teks:
   teks.write('Ini contoh teks')
```

## Pembacaan (*read*) file

```{python}
with open('simpel.txt', 'w+') as teks:
   print(teks.read())
   teks.write('100 + 200 = 300')
   print(teks.read())
```